# Linear Regression for house pricing

<i>Konstantin Kuzmin, 2019</i>

<b>Task</b>: Given set of house sales in the neighborhood last year calculate fair price for my house using linear regression.<br><b>Data</b>: Features include number of bedrooms, full bath, half bath, stories, garage spots, year when property was built, square footage, land size, listed price, Y/N upgrades flag, Y/N rented flag, number from 0 to 1 experessing proximity to a recently opened neighborhood cave, Y/N pool flag, Y/N cul-de-sac flag, Y/N facing greenbelt flag.

### Initial setup

In [3]:
!pip install mxnet

    100% |████████████████████████████████| 28.4MB 933kB/s eta 0:00:01
    100% |████████████████████████████████| 61kB 17.9MB/s ta 0:00:01
tensorflow 1.3.0 requires tensorflow-tensorboard<0.2.0,>=0.1.0, which is not installed.
  Found existing installation: requests 2.18.4
    Uninstalling requests-2.18.4:
      Successfully uninstalled requests-2.18.4


In [4]:
import mxnet as mx

In [99]:
isTest = True

In [100]:
# The code was removed by Watson Studio for sharing.

In [101]:
print(data.head())
if isTest:
    print("\nRunning test mode")
else:
    print("\nData set is shown above. We have total 73 training examples.\nEach one is represented by 15 features. Now the feature set should be in the <i>hpinput</i> and price for each house should be in the <i>hpoutput</i> data frame.")

      0  1       2
0  2104  3  399900
1  1600  3  329900
2  2400  3  369000
3  1416  2  232000
4  3000  4  539900

Running test mode


Converting to Numpy arrays.

In [108]:
Xorig = datainput.values
Y = dataoutput.values
# print("Shape of X: ", X.shape)
# print("Shape of Y: ", Y.shape)

### Apply linear regression using gradient descent


In [114]:
Xorig = Xorig.astype(float)
Xstd = Xorig.std(axis=0)
Xmean = Xorig.mean(axis=0)
X = preprocessing.scale(Xorig)

m = X[:,0].size # number of training examples
X = np.append(np.ones([m,1], dtype = int), X, axis = 1)

In [115]:
n = X[0,:].size # number of features

# define parameter vector
Theta = np.zeros([n, 1], dtype = int)

# define our hypothesis function
def h(parX, parTheta):
    return np.dot(parX, parTheta)

# define cost function
def costFunction(parX, parY, parTheta):
    mt = parX[:,0].size
    return 1/(2*mt)*np.sum(np.square(h(parX, parTheta) - parY))

costFunction(X, Y, Theta)

65591548106.457443

In [116]:
# define Gradient Descent function
def gradientDescent(alpha, parTheta, parX, parY):
    mt = parX[:, 0].size
    outTheta = parTheta - alpha/mt*np.dot(np.transpose(X), h(X, Theta) - Y)
    return outTheta

In [117]:
for x in range(1000):
    alpha = 0.01
    Theta = gradientDescent(alpha, Theta, X, Y)
print(costFunction(X, Y, Theta))

2043498948.14


In [118]:
Theta

array([[ 340397.96353532],
       [ 108742.65627238],
       [  -5873.22993383]])

In [132]:
x = [[1650, 3]]
x = np.divide(x - Xmean, Xstd)
x = np.append([[1]], x, axis = 1)
h(x, Theta)

array([[ 293221.86768361]])

In [90]:
x = np.array([[5,2,1,2,2,1993,3080,0.174,330000,0,0,1,0,0,0]])
x = preprocessing.scale(x)
x.shape
x = np.append(np.ones([1,1], dtype = int), x, axis = 1)
print(x)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.]])

In [91]:
h(x, Theta)

array([[ 359049.82191781]])

In [76]:
Theta

array([[  3.59049822e+05],
       [  2.13764210e+03],
       [ -1.27750509e+03],
       [ -2.40778683e+02],
       [ -1.29735064e+03],
       [ -2.55454357e+01],
       [  2.62289987e+03],
       [  8.01345788e+02],
       [  2.11127744e+03],
       [  4.76068602e+04],
       [  2.09775682e+03],
       [ -7.30520404e+02],
       [ -3.02713200e+02],
       [  8.07124392e+02],
       [  4.35631917e+02],
       [  3.38338421e+02]])

### Normal equation
First let's try normal equation to find optimal Theta which would allow to minimize cost function.
According to hormal equation Theta is calculated as follows:<br>
Theta = ($X^{T}$X$)^{-1}$$X^{T}$Y

In [134]:
X = np.append(np.ones([m,1], dtype = int), Xorig, axis = 1)
# Calculate Theta as inverse of X transposed multiplied by X, then multiplied to X transposed and by Y.
Theta = np.dot(np.dot(np.linalg.inv(np.dot(np.transpose(X), X)), np.transpose(X)), Y)
Theta
# Define input parameters for my house
# x = np.array([[1,5,2,1,2,2,1993,3080,0.174,330000,0,0,1,0,0,0]])

x = [[1, 1650, 3]]
h(x, Theta)

array([[ 293081.46433489]])

Calculate price of my house using Theta derived from normal equation.

In [24]:
Price = np.dot(x, Theta)[0,0]
Price = round(Price, 2)
print("Price of the house: $", '{:,}'.format(Price))

Price of the house: $ 326,560.75
